server:
  port: 8080
management:
  port: 8081
endpoints:
  shutdown:
    enabled: true
---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-cd
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
hello:
  backgroundcolor: yellow
---

spring:
  profiles: autosmall
hello:
  backgroundcolor: red

---

spring:
  profiles: autolarge
hello:
  backgroundcolor: red

---

spring:
  profiles: man
hello:
  backgroundcolor: magenta

---

spring:
  profiles: prod
hello:
  backgroundcolor: white
